#!/bin/bash

NFS_STATUS=$(systemctl is-active nfs-server 2>/dev/null)

if [ "$NFS_STATUS" != "active" ]; then
    echo "양호: NFS 서비스가 비활성화되어 있습니다."
else
   
    if [ -f /etc/exports ]; then
        RESTRICT_CHECK=$(grep "*" /etc/exports | grep -v "#")
        if [ -z "$RESTRICT_CHECK" ]; then
            echo "양호: NFS 공유 시 모든 호스트접근이 제한되어 있습니다."
        else
            echo "취약: NFS 공유 설정에 와일드카드가 사용되었습니다."
            echo "상세 내용: $RESTRICT_CHECK"
        fi
    else
        echo "양호: NFS 서비스는 활성화되어 있으나 설정 파일이 존재하지 않습니다."
    fi
fi
